import type { Metadata } from "next";
import "../assets/css/globals.css";

export const metadata: Metadata = {
  title: "TTA-110",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">
      <body
        className={` bg-neutral-200 antialiased min-h-screen w-full`}
      >
        {children} 
      </body>
    </html>
  );
}
